---
title: "Untitled"
author: "Gabriel Silva Cheinquer (4266390), Ege Basaran (8787433)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1

### Data preparation

In addition to the Facebook network you have used in the Learning-based exercise, you will use the Highschool network here.

[Download the “Highschool_network_att.csv”, “Highschool_network_att.csv”, and “LargeFacebook_network_att.csv”, and “LargeFacebook_network_edge.csv” from BrightSpace. Import the `.csv` data into `R` and build the two networks.]{.underline}

## Question 1 (3 points): 

-   [For both the High-school and Facebook networks, calculate the shortest path lengths between every pair of two nodes. How many percentage of nodes can be reached within 6 path lengths? Does “six degree of separation” apply to each network?]{.underline}

-   [Study the degree distribution of these two networks, are they similar? Then use degree distribution to explain the degree of separation you answered above.]{.underline}

You can calculate the shortest path lengths between every pair of two nodes using igraph package:

``` R
distances(Highschool, 
          v = V(Highschool), 
          to = V(Highschool), 
          mode = c("all", "out", "in"), 
          weights = NULL) 

#Shortest path lengths between every pair of two nodes in the network You can consider to use histogram with percentile to study the shortest path lengths and the degree distribution:
```

You can consider to use histogram with percentile to study the shortest path lengths and the degree distribution:

![One important stand of community detection algorithm is based on [***modularity***]{.underline}, which tries to maximize the difference between the actual number of edges in a community and the expected number of edges in the community. However, optimizing modularity in a network is NP-hard, therefore have to use heuristics.](images/clipboard-4108311466.png)
